language: node_js
sudo: false
node_js:
  - "6"
script:
  - npm test
addons:
    code_climate:
        repo_token: b510733d1ea20597bdea8c046e41f7dedebd05b9e8f8324f833c089f97d27da8
    apt:
        packages:
          - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &        