language: node_js
sudo: false
node_js:
  - "6"
script:
  - --chmod=+x ./push-docs-to-gh.sh
  - npm install
  - npm run coverage
  - npm run docs
after_success:
  - npm run coverage:codeclimate
  - ./push-docs-to-gh.sh
addons:
    apt:
        packages:
          - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &        